server:
  host: ""
  port: 1883
  sendcommands: true
devices:
  plugs: 
    idlist: [hvac-f, hvac-r]
    command: "switchbot/blower-ctrl/plug/%s/set"
  switches: 
    idlist: []
    command: "" 
cloudapi:
  baseurl: "https://iot-rewards.ngrok.app/"
  telemetry: "api/telemetry"
  device: "api/device"
  cron: "api/cron"
  callsenabled: false
  