server:
  host: "192.168.50.86"
  port: 1883
  sendcommands: true
devices:
  plugs: ["hvac-f", "hvac-r"]
cloudapi:
  baseurl: "https://iot-rewards.ngrok.app/"
  telemetry: "api/telemetry"
  device: "api/device"ifcon
  cron: "api/cron"
  callsenabled: false
  